---
title: "maps"
author: "William Haslam"
date: "18/02/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidycensus)
library(dplyr)
library(tidyverse)
census_api_key("098f24a922cbdaf298689f71c1d4b9f2426b767b")



```


```{r echo = FALSE, include = FALSE}

racevars <- c(White = "B02001_002", 
              Black = "B02001_003", 
              Asian = "B02001_005",
              Hispanic = "B03003_003")

middlesex <- get_acs(geography = "tract",
                  variables = racevars, 
                  year = 2018,
                  state = "NY",
                  county = "New York County",
                  geometry = TRUE,
                  summary_var = "B02001_001") 


```


```{r New York, echo = FALSE}

middlesex %>%
  mutate(Percent = 100 * (estimate / summary_est)) %>%
  ggplot(aes(fill = Percent, color = Percent)) +
  facet_wrap(~ variable) +
  geom_sf() +
  scale_fill_viridis_c(direction = -1) +
  scale_color_viridis_c(direction = -1) +
  labs(title = "Racial geography of New York County, New York",
       caption = "Source: American Community Survey 2014-2018") +
  theme_void()

```

